"""add last_read_message_id to chatparticipant

Revision ID: 44f474a36386
Revises: f314b303aa77
Create Date: 2026-03-01 14:01:07.034685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44f474a36386'
down_revision: Union[str, Sequence[str], None] = 'f314b303aa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatparticipant', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatparticipant', 'last_read_message_id')
    # ### end Alembic commands ###
