"""add_chat_tables_refactor_message

Revision ID: f314b303aa77
Revises: 33910ca87ef1
Create Date: 2026-03-01 13:29:25.696737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f314b303aa77'
down_revision: Union[str, Sequence[str], None] = '33910ca87ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatparticipant_chat_id'), 'chatparticipant', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chatparticipant_user_id'), 'chatparticipant', ['user_id'], unique=False)
    op.execute("DELETE FROM message")
    op.add_column('message', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_message_receiver_id'), table_name='message')
    op.create_index(op.f('ix_message_chat_id'), 'message', ['chat_id'], unique=False)
    op.drop_constraint(op.f('message_receiver_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'])
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_receiver_id_fkey'), 'message', 'user', ['receiver_id'], ['id'])
    op.drop_index(op.f('ix_message_chat_id'), table_name='message')
    op.create_index(op.f('ix_message_receiver_id'), 'message', ['receiver_id'], unique=False)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('message', 'is_system')
    op.drop_column('message', 'chat_id')
    op.drop_index(op.f('ix_chatparticipant_user_id'), table_name='chatparticipant')
    op.drop_index(op.f('ix_chatparticipant_chat_id'), table_name='chatparticipant')
    op.drop_table('chatparticipant')
    op.drop_table('chat')
    # ### end Alembic commands ###
